
export const SET_FISHMARK_POSITION = "SET_FISHMARK_POSITION"
export const GET_FISHMARK_POSITION = "GET_FISHMARK_POSITION"
export const UPDATE_FISHMARK_DATA = "UPDATE_FISHMARK_DATA"
export const MOVE_TO_FISHMARK_POSITION = "MOVE_TO_FISHMARK_POSITION"
export const DELETE_FISHMARK_POSITION = "DELETE_FISHMARK_POSITION"
export const LOAD_FISHMARKS_POSITIONS_PENDING = "LOAD_FISHMARKS_POSITIONS_PENDING"

export const SUCCESS_LOAD_FISHMARKS_POSITIONS = "SUCCESS_LOAD_FISHMARKS_POSITIONS"
export const FAILED_LOAD_FISHMARKS_POSITIONS = "FAILED_LOAD_FISHMARKS_POSITIONS"
export const FAILED_SET_FISHMARK_POSITION = "FAILED_SET_FISHMARK_POSITION"
export const SUCCESS_SET_FISHMARK_POSITION = "SUCCESS_SET_FISHMARK_POSITION"
export const LOAD_FISHMARKS_POSITIONS = "LOAD_FISHMARKS_POSITIONS"



export const OAUTH_URL = "http://fishmap.test.pl:3000/auth/google"
//export const OAUTH_URL = "https://yqxcjoicsc.localtunnel.me/auth/google"
export const API_ENDPOINT = "192.168.0.115:3000"

export const SET_USER_DATA = "SET_USER_DATA"

export const LOGOUT = "LOGOUT"
export const LOGIN = "LOGIN"

export const FAILED_SET_TOKEN = "FAILED_SET_TOKEN"
export const SUCCESS_SET_TOKEN = "SUCCESS_SET_TOKEN"
export const VERIFY_TOKEN = "VERIFY_TOKEN"
export const SUCCESS_REMOVE_TOKEN = "SUCCESS_REMOVE_TOKEN"
export const FAILED_REMOVE_TOKEN = "FAILED_REMOVE_TOKEN"
export const SUCCESS_VERIFY_TOKEN = "SUCCESS_VERIFY_TOKEN"
export const FAILED_VERIFY_TOKEN = "FAILED_VERIFY_TOKEN"

export const SUCCESS_GET_USER_LOCATION = "SUCCESS_GET_USER_LOCATION"
export const FAILED_GET_USER_LOCATION  = "FAILED_GET_USER_LOCATION"
export const GET_USER_LOCATION = "GET_USER_LOCATION"
export const LOAD_WAYPOINTS_ON_PUSH = "LOAD_WAYPOINTS_ON_PUSH"
export const SUCCESS_UPDATE_WAYPOINTS_ON_PUSH =  "SUCCESS_UPDATE_WAYPOINTS_ON_PUSH"
export const FAILED_UPDATE_WAYPOINT_ON_PUSH = "FAILED_UPDATE_WAYPOINT_ON_PUSH"
export const INCREMENT_SEED = "INCREMENT_SEED"

export const DELETE_WAYPOINT = "DELETE_WAYPOINT"
export const SUCCESS_DELETE_WAYPOINT = "SUCCESS_DELETE_WAYPOINT"
export const FAILED_DELETE_WAYPOINT = "FAILED_DELETE_WAYPOINT"