
export const SET_FISHMARK_POSITION = "SET_FISHMARK_POSITION"
export const GET_FISHMARK_POSITION = "GET_FISHMARK_POSITION"
export const UPDATE_FISHMARK_DATA = "UPDATE_FISHMARK_DATA"
export const MOVE_TO_FISHMARK_POSITION = "MOVE_TO_FISHMARK_POSITION"
export const DELETE_FISHMARK_POSITION = "DELETE_FISHMARK_POSITION"
export const LOAD_POSITIONS = "LOAD_POSITIONS"

export const UPLOAD_FISHMARK_POSITIONS = "UPLOAD_FISHMARK_POSITIONS"
export const FAILED_UPLOAD_FISHMARK_POSITIONS = "FAILED_UPLOAD_FISHMARK_POSITIONS"
export const FAILED_SET_FISHMARK_POSITION = "FAILED_SET_FISHMARK_POSITION"
export const SUCCESS_FISHMARK_POSITION = "SUCCESS_FISHMARK_POSITION"
export const SUCCESS_UPLOAD_FISHMARK_POSITIONS = "SUCCESS_UPLOAD_FISHMARK_POSITIONS"



export const OAUTH_URL = "http://fishmap.test.pl:3000/auth/google"
//export const OAUTH_URL = "https://yqxcjoicsc.localtunnel.me/auth/google"
export const API_ENDPOINT = "192.168.0.115:3000"

export const SET_USER_DATA = "SET_USER_DATA"

export const LOGOUT = "LOGOUT"
export const LOGIN = "LOGIN"

export const FAILED_SET_TOKEN = "FAILED_SET_TOKEN"
export const SUCCESS_SET_TOKEN = "SUCCESS_SET_TOKEN"
export const VERIFY_TOKEN = "VERIFY_TOKEN"

export const SUCCESS_GET_USER_LOCATION = "SUCCESS_GET_USER_LOCATION"
export const FAILED_GET_USER_LOCATION  = "FAILED_GET_USER_LOCATION"